### ISSUE TITLE
display:inline-block兼容ie6/7的写法

### ISSUE THREAD

**Issue by paddingme** [paddingme/Learning-HTML-CSS#20]
[display:inline-block兼容ie6/7的写法](http://www.phpvar.com/archives/2211.html)

``` css
div {
  display:inline-block;
  *display:inline; 
  *zoom:1;
} 

```
