### ISSUE TITLE
CSS 通配符

### ISSUE THREAD

**Issue by paddingme** [paddingme/Learning-HTML-CSS#37]
* 会影响 css 属性继承。

例如 

```html
<p>xx<span>oo</span></p>
```
```css
* {
  font-size: 14px;
} 

p { font-size: 16px}
````

span 不会继承 16，而会默认接受 通配符字体大小。

可以使用：

```css
* {
  font-size:inhreit;
}
```
修改

使用 通配符对 网页渲染曾在性能问题，因为需要不断继承，改写通配符的样式。

另如上所述不便于维护，debug。

所以 写 通配符的 都没小 JJ。
